### ISSUE TITLE
Merge cookbooks?

### ISSUE THREAD

**Issue by dmyers** [hw-cookbooks/gluster#1]
Would it be possible to merge this cookbook with another?

The default recipe in this one installs both the client and server packages. This other cookbook has quite a bit of recipes too.

https://github.com/shortdudey123/chef-gluster

The only thing I wish for is to be able to move some of the logic involved in setting up a volume and peering nodes as chef definitions.

**Comment by webframp** [comment]
I suppose you'll have to confirm with the other authors, but I have no problem with that. Our usage of cluster is minimal now, so we'd be happy hand off

**Comment by jarosser06** [comment]
+1 It would be nice to have gluster in the supermarket replaced by biola/chef-gluster

**Comment by shortdudey123** [comment]
@webframp I have taken over the other gluster cookbook (formally biola/chef-gluster)

**Comment by shortdudey123** [comment]
Finally uploaded my cookbook version to the supermarket
https://supermarket.chef.io/cookbooks/gluster

So this can be closed
